### ISSUE TITLE
Resource actions are attached to every Subclass of the Resource class

### ISSUE THREAD

**Issue by dexax** [beachmachine/ngx-resource-factory#15]
I am using the `@ResourceAction` decorator pretty often in my rest resources 
but there is some problem with it. 
Every new defined Resource subclass got all the resource actions inherited from their "subclass siblings". 
I am aware that the TS classes aren't in fact real classes so the way the new props are added to the prototype can lead to the described problem.

**Comment by anx-astocker** [comment]
Hi!
I will try to reproduce the issue and will let you know if I found a feasible solution to it.

**Comment by anx-astocker** [comment]
Hi again!
The now released version 1.1.0 of ngx-resource-factory fixes the issue. This is also covered by unit-tests now. 

Have a nice day!
